### ISSUE TITLE
conv0 conv10卷积层的作用

### ISSUE THREAD

**Issue by VVZzzz** [wuyang0329/unet#16]
我看到你的代码input之后接的是一个conv0+pool0 , 还有最后加了 conv10 . 这两个作用是什么? 谢谢解答!

**Comment by wuyang0329** [comment]
> 我看到你的代码input之后接的是一个conv0+pool0 , 还有最后加了 conv10 . 这两个作用是什么? 谢谢解答!

我在原网络的基础之上加了一层卷积，由于unet网络是对称的所以在前面加了一层以后最后也要加上一层使得网络对称，加这两层的目的还是为了提升效果，之前的网络都是从64个卷积开始卷积，我想试试从32个卷积核上开始卷积效果如何

**Comment by VVZzzz** [comment]
好的 谢谢 ^_^
