### ISSUE TITLE
Error when checking target: expected conv2d_24 to have shape (None, 512, 512, 1) but got array with shape (2, 512, 512, 3)

### ISSUE THREAD

**Issue by reachsak** [wuyang0329/unet#17]
Hi, I am trying to use model_v2 which is for RGB image and all of my image is already RGB images but still got this error. 
What's seem to be going wrong here ?

**Comment by reachsak** [comment]
I'm new to Deep learning here, here is the code ,  thanks for your helps
<img width="1412" alt="Screen Shot 2019-08-15 at 2 47 01 PM" src="https://user-images.githubusercontent.com/53211721/63080560-91cc4500-bf6b-11e9-9c3b-03122559cd33.png">
<img width="864" alt="Screen Shot 2019-08-15 at 2 42 52 PM" src="https://user-images.githubusercontent.com/53211721/63080563-942e9f00-bf6b-11e9-81d3-6f3090c5ed03.png">

**Comment by reachsak** [comment]
here is my train.py , i cross out some code since i am preparing my own dataset. 
<img width="1056" alt="Screen Shot 2019-08-15 at 2 52 14 PM" src="https://user-images.githubusercontent.com/53211721/63080881-6a29ac80-bf6c-11e9-901d-379ed8251456.png">

**Comment by reachsak** [comment]
and here is my image format 
<img width="512" alt="Screen Shot 2019-08-15 at 2 55 31 PM" src="https://user-images.githubusercontent.com/53211721/63081031-c5f43580-bf6c-11e9-849d-54f6e86198e4.png">

**Comment by wuyang0329** [comment]
> I'm new to Deep learning here, here is the code , thanks for your helps
> <img alt="Screen Shot 2019-08-15 at 2 47 01 PM" width="1412" src="https://user-images.githubusercontent.com/53211721/63080560-91cc4500-bf6b-11e9-9c3b-03122559cd33.png">
> <img alt="Screen Shot 2019-08-15 at 2 42 52 PM" width="864" src="https://user-images.githubusercontent.com/53211721/63080563-942e9f00-bf6b-11e9-81d3-6f3090c5ed03.png">

Maybe you could modify label_color_mode to grayscale

**Comment by reachsak** [comment]
> > I'm new to Deep learning here, here is the code , thanks for your helps
> > <img alt="Screen Shot 2019-08-15 at 2 47 01 PM" width="1412" src="https://user-images.githubusercontent.com/53211721/63080560-91cc4500-bf6b-11e9-9c3b-03122559cd33.png">
> > <img alt="Screen Shot 2019-08-15 at 2 42 52 PM" width="864" src="https://user-images.githubusercontent.com/53211721/63080563-942e9f00-bf6b-11e9-81d3-6f3090c5ed03.png">
> 
> Maybe you could modify label_color_mode to grayscale

thanks ,your solution works , Now i successfully train the RGB image

**Comment by reachsak** [comment]
But now the problem is , i used the trained .hdf5 data and model_v2 to predict my test rgb image but got the following error , my image rgb , 512x512 , png .. 
<img width="631" alt="Screen Shot 2019-08-15 at 4 31 33 PM" src="https://user-images.githubusercontent.com/53211721/63087138-9ac51280-bf7b-11e9-8e40-06f6b0a89147.png">
<img width="1037" alt="Screen Shot 2019-08-15 at 4 31 21 PM" src="https://user-images.githubusercontent.com/53211721/63087174-aadcf200-bf7b-11e9-8207-838422748ec9.png">

**Comment by reachsak** [comment]
when i try with the gray test image, 512 x512 gray  , i got the white image as predicted result 
<img width="628" alt="Screen Shot 2019-08-15 at 4 44 30 PM" src="https://user-images.githubusercontent.com/53211721/63087292-00b19a00-bf7c-11e9-882a-122f9527acbc.png">

**Comment by reachsak** [comment]
it seem that the code only read the grayscale test image,  is there the problem with my "rgb" test image format ?

**Comment by reachsak** [comment]
> it seem that the code only read the grayscale test image, is there the problem with my "rgb" test image format ?

i also try converting using the RGB of .png .tif .jpg version but still got the same error , so far it only work with the grayscale .png image.

**Comment by reachsak** [comment]
> > it seem that the code only read the grayscale test image, is there the problem with my "rgb" test image format ?
> 
> i also try converting using the RGB of .png .tif .jpg version but still got the same error , so far it only work with the grayscale .png image.

**Comment by reachsak** [comment]
how should i modified the code so that able make the prediction on RGB image :)

**Comment by wuyang0329** [comment]
You could check the Camvid dataset images mode and make sure that your dataset is similar to it.
And you should train enough on your dataset.
