### ISSUE TITLE
Training the data in the data with the provided code, the prediction result is all white, because the number of training is too small? Or is there a problem with the parameter settings?

### ISSUE THREAD

**Issue by 1054816178** [wuyang0329/unet#19]

**Comment by wuyang0329** [comment]
maybe  you should check the train data's formart

**Comment by 1054816178** [comment]
the data's formart is not "tif"?

**Comment by 1054816178** [comment]
另外我想问您一下，您制作的label图片是3通道的且内容都是一样的，这与单通道的label在二分类时有区别吗?还是说这仅仅只是格式的要求？

**Comment by wuyang0329** [comment]
你看你是做二分类还是多分类吧，多分类不能用tif格式的图片，多分类的图片类型最好是跟Camvid数据集一致，Camvid数据集用我这个代码训练是完全没有问题的，如果是二分类，你就可以选择用tif或者其他格式的都是可以的。
label图片的通道数是与网络结构的定义有关的，如果你的最后一层输入是单通道，那么label就是单通道，只要前后保持一直就可以了，跟格式没有关系，格式的选择还是要由网络的定义来决定

**Comment by 1054816178** [comment]
哦是这样的，我懂了。谢谢您分享的代码和指导
