### ISSUE TITLE
for k in range(len(img)): TypeError: object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by Sarthak2101** [wuyang0329/unet#4]
Hi.
I'm using google colab to run the code for training my own dataset. while running test.py i face this error. Please help. Thanks in advance. Here's the detailed error:

Traceback (most recent call last):
  File "test.py", line 50, in <module>
    dp.saveResult(np.asarray([results[0]]),img_size,name.split('.')[0])
  File "/content/drive/My Drive/unet-master3/data.py", line 128, in saveResult
    for k in range(len(img)):
TypeError: object of type 'NoneType' has no len()

**Comment by wuyang0329** [comment]
> Hi.
> I'm using google colab to run the code for training my own dataset. while running test.py i face this error. Please help. Thanks in advance. Here's the detailed error:
> 
> Traceback (most recent call last):
> File "test.py", line 50, in 
> dp.saveResult(np.asarray([results[0]]),img_size,name.split('.')[0])
> File "/content/drive/My Drive/unet-master3/data.py", line 128, in saveResult
> for k in range(len(img)):
> TypeError: object of type 'NoneType' has no len()


you  could try  replace  the  saveResult  function  with  this one：
    def saveResult(self, npyfile, size, name, threshold=127):
        for i, item in enumerate(npyfile):
            img = self.labelVisualize(self.num_class, COLOR_DICT, item) if self.flag_multi_class else item[:, :, 0]
            img = cv2.resize(img, size, interpolation=cv2.INTER_CUBIC)
            ret, thresh = cv2.threshold(img, threshold / 255.0, 1.0, cv2.THRESH_TOZERO)
            cv2.imwrite(os.path.join(self.save_path, ("%s_predict." + self.img_type) % (name)), thresh)

**Comment by Sarthak2101** [comment]
> > Hi.
> > I'm using google colab to run the code for training my own dataset. while running test.py i face this error. Please help. Thanks in advance. Here's the detailed error:
> > Traceback (most recent call last):
> > File "test.py", line 50, in
> > dp.saveResult(np.asarray([results[0]]),img_size,name.split('.')[0])
> > File "/content/drive/My Drive/unet-master3/data.py", line 128, in saveResult
> > for k in range(len(img)):
> > TypeError: object of type 'NoneType' has no len()
> 
> **you could try replace the saveResult function with this one：**
> 
> ```
>  def saveResult(self, npyfile, size, name, threshold=127):
>         for i, item in enumerate(npyfile):
>             img = self.labelVisualize(self.num_class, COLOR_DICT, item) if self.flag_multi_class else item[:, :, 0]
>             img = cv2.resize(img, size, interpolation=cv2.INTER_CUBIC)
>             ret, thresh = cv2.threshold(img, threshold / 255.0, 1.0, cv2.THRESH_TOZERO)
>             cv2.imwrite(os.path.join(self.save_path, ("%s_predict." + self.img_type) % (name)), thresh)
> ```

@wuyang0329 
Thanks for the help. This rectifies the error, but the predictions are still not being saved. Help me out with please.

**Comment by wuyang0329** [comment]
> > > Hi.
> > > I'm using google colab to run the code for training my own dataset. while running test.py i face this error. Please help. Thanks in advance. Here's the detailed error:
> > > Traceback (most recent call last):
> > > File "test.py", line 50, in
> > > dp.saveResult(np.asarray([results[0]]),img_size,name.split('.')[0])
> > > File "/content/drive/My Drive/unet-master3/data.py", line 128, in saveResult
> > > for k in range(len(img)):
> > > TypeError: object of type 'NoneType' has no len()
> > 
> > 
> > **you could try replace the saveResult function with this one：**
> > ```
> >  def saveResult(self, npyfile, size, name, threshold=127):
> >         for i, item in enumerate(npyfile):
> >             img = self.labelVisualize(self.num_class, COLOR_DICT, item) if self.flag_multi_class else item[:, :, 0]
> >             img = cv2.resize(img, size, interpolation=cv2.INTER_CUBIC)
> >             ret, thresh = cv2.threshold(img, threshold / 255.0, 1.0, cv2.THRESH_TOZERO)
> >             cv2.imwrite(os.path.join(self.save_path, ("%s_predict." + self.img_type) % (name)), thresh)
> > ```
> 
> @wuyang0329
> Thanks for the help. This rectifies the error, but the predictions are still not being saved. Help me out with please.

Maybe you need to  use  data_Pretreatment.py to preprocess your train dataset. 
Have a try

**Comment by Sarthak2101** [comment]
@wuyang0329 
I used data_Pretreatment.py to preprocess my entire dataset. Now predictions are generated as all black. What should I do for that?
Thanks again

**Comment by wuyang0329** [comment]
> @wuyang0329
> I used data_Pretreatment.py to preprocess my entire dataset. Now predictions are generated as all black. What should I do for that?
> Thanks again

I am tring to fix my  project and  readme，you can  wait  for them。
Maybe  you could star the project.  Thanks

**Comment by wuyang0329** [comment]
> @wuyang0329
> I used data_Pretreatment.py to preprocess my entire dataset. Now predictions are generated as all black. What should I do for that?
> Thanks again

The code has been updated , you can have a try in your dataset.
Notice the image type and the image color mode / label color mode, default value is RGB.

**Comment by Sarthak2101** [comment]
> > @wuyang0329
> > I used data_Pretreatment.py to preprocess my entire dataset. Now predictions are generated as all black. What should I do for that?
> > Thanks again
> 
> The code has been updated , you can have a try in your dataset.
> Notice the image type and the image color mode / label color mode, default value is RGB.

Hey thanks a lot i could generate predictions this time. This proved very helpful :)
