### ISSUE TITLE
为什么CamVid Dataset的label图片都是全黑的？能成功？

### ISSUE THREAD

**Issue by zhyantao** [wuyang0329/unet#6]
图片截图如下：
![image](https://user-images.githubusercontent.com/25874888/56363469-e5798c80-621e-11e9-9266-38e500731615.png)

**Comment by wuyang0329** [comment]
> 图片截图如下：
> ![image](https://user-images.githubusercontent.com/25874888/56363469-e5798c80-621e-11e9-9266-38e500731615.png)
不是全黑的，他的标签值是从1开始的低值像素，你用工具打开就可以看到了

**Comment by toooney** [comment]
OK, thankyou very much.

Yan-tao Zhang

wuyang0329 <notifications@github.com>编写：

**Comment by wuyang0329** [comment]
只是像素值较低不是全黑的，用软件打开可以看到像素值




| |
Young
|
|
邮箱：wuyang0329@163.com
|

Signature is customized by Netease Mail Master

在2019年06月26日 14:51，Zh YT 写道：

Closed #6.
